3. Import the required packages with their customary aliases: pandas, numpy, matplotlib.pyplot, seaborn

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

4. Use the %matplotlib inline magic command so plots show in the notebook without having to call plt.show() every time. 

In [4]:
%matplotlib inline


5. Using pandas read_csv method, read the GDP dataset as a DataFrame called gdp_df. Look at first 6 rows

In [5]:
gdp_df = pd.read_csv("../Data/gdp_percapita.csv", nrows=6868)
print(gdp_df.head(6))

  Country or Area  Year        Value  Value Footnotes
0     Afghanistan  2019  2065.036398              NaN
1     Afghanistan  2018  2033.779002              NaN
2     Afghanistan  2017  2058.383832              NaN
3     Afghanistan  2016  2057.062164              NaN
4     Afghanistan  2015  2068.265904              NaN
5     Afghanistan  2014  2102.385234              NaN


6. Repeat for internet dataset called internet_df and look at first 6 rows

In [6]:
internet_df = pd.read_csv("../Data/internet_use.csv", nrows=4495)
print(internet_df.head(6))

  Country or Area  Year     Value  Value Footnotes
0     Afghanistan  2014  6.390000              NaN
1     Afghanistan  2013  5.900000              NaN
2     Afghanistan  2012  5.454545              NaN
3     Afghanistan  2011  5.000000              NaN
4     Afghanistan  2010  4.000000              NaN
5     Afghanistan  2009  3.550000              NaN


7. Look at the shape of each DataFrame. How many rows? How many columns? 

In [9]:
internet_df.shape

(4495, 4)

internet_df has 4495 rows and 4 columns

In [10]:
gdp_df.shape

(6868, 4)

gdp_df has 6868 rows and 4 columns

8. Take a look at the datatypes for the columns in each DataFrame

In [11]:
internet_df.dtypes

Country or Area     object
Year                 int64
Value              float64
Value Footnotes    float64
dtype: object

In [12]:
gdp_df.dtypes

Country or Area     object
Year                 int64
Value              float64
Value Footnotes    float64
dtype: object

9. Take a look at the last 10 rows of each DataFrame

In [13]:
internet_df.tail(10)

Country or Area  Year     Value  Value Footnotes
4485        Zimbabwe  2002  3.994356              NaN
4486        Zimbabwe  2001  0.799846              NaN
4487        Zimbabwe  2000  0.401434              NaN
4488        Zimbabwe  1999  0.161676              NaN
4489        Zimbabwe  1998  0.081648              NaN
4490        Zimbabwe  1997  0.033080              NaN
4491        Zimbabwe  1996  0.016790              NaN
4492        Zimbabwe  1995  0.007684              NaN
4493        Zimbabwe  1994  0.001739              NaN
4494        Zimbabwe  1990  0.000000              NaN

In [14]:
gdp_df.tail(10)

Country or Area  Year        Value  Value Footnotes
6858        Zimbabwe  1999  3600.849291              NaN
6859        Zimbabwe  1998  3653.920016              NaN
6860        Zimbabwe  1997  3580.048793              NaN
6861        Zimbabwe  1996  3520.430146              NaN
6862        Zimbabwe  1995  3226.413930              NaN
6863        Zimbabwe  1994  3263.934978              NaN
6864        Zimbabwe  1993  3033.504852              NaN
6865        Zimbabwe  1992  3054.889178              NaN
6866        Zimbabwe  1991  3426.598094              NaN
6867        Zimbabwe  1990  3324.348171              NaN

10. Drop the value footnotes column from both DataFrames. Check that it worked. 

In [21]:
internet_df = internet_df.drop(['Value Footnotes'], axis = 1)

In [22]:
print(internet_df)

     Country or Area  Year     Value
0        Afghanistan  2014  6.390000
1        Afghanistan  2013  5.900000
2        Afghanistan  2012  5.454545
3        Afghanistan  2011  5.000000
4        Afghanistan  2010  4.000000
...              ...   ...       ...
4490        Zimbabwe  1997  0.033080
4491        Zimbabwe  1996  0.016790
4492        Zimbabwe  1995  0.007684
4493        Zimbabwe  1994  0.001739
4494        Zimbabwe  1990  0.000000

[4495 rows x 3 columns]


In [23]:
gdp_df = gdp_df.drop(['Value Footnotes'], axis = 1)

In [24]:
print(gdp_df)

     Country or Area  Year        Value
0        Afghanistan  2019  2065.036398
1        Afghanistan  2018  2033.779002
2        Afghanistan  2017  2058.383832
3        Afghanistan  2016  2057.062164
4        Afghanistan  2015  2068.265904
...              ...   ...          ...
6863        Zimbabwe  1994  3263.934978
6864        Zimbabwe  1993  3033.504852
6865        Zimbabwe  1992  3054.889178
6866        Zimbabwe  1991  3426.598094
6867        Zimbabwe  1990  3324.348171

[6868 rows x 3 columns]


11. Change the columns for the GDP DataFrame to 'Country', 'Year', 'GDP_Per_Capita'